models:
  - type: main
    engine: google_genai
    model: gemini-2.0-flash-lite

rails:
  config:
    polygraf:
      server_endpoint: "https://governance.api.polygraf.ai/gcp/pii/text-detect"
      input:
        entities:
          - Email
          - Person
          - Phone
      output:
        entities:
          - Email
          - Person
          - Phone

  input:
    flows:
      - polygraf detect pii on input

  output:
    flows:
      - polygraf detect pii on output
